---
# handlers file for ansible-role-limits

- name: daemon reload
  systemd:
    name: "{{ item['name'] }}"
    state: restarted
    daemon_reload: yes
  loop: "{{ limits_systemd_service | flatten(levels=1) }}"
